apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
spec:
  containers:
  - name: redis-cache
    image: redis:4.0.14
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.1"
        memory: 256m
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-cache-config
        items:
        - key: redis-config
          path: redis.conf
